name: Release Build and Attach

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Attach Artifacts
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
  
      - name: Version
        run: go version
  
      # Create a zip file of the source code
      - name: Create source code zip
        run: zip -r prowl-source-$(git describe --tags --abbrev=0).zip .

      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: go test -v ./...

      # Upload the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: prowl-$(git describe --tags --abbrev=0).zip
          path: ./prowl

      # Attach artifacts to the release
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./prowl-$(git describe --tags --abbrev=0).zip
          asset_name: prowl-$(git describe --tags --abbrev=0).zip
          asset_content_type: application/zip

      - name: Attach source code zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./prowl-source-$(git describe --tags --abbrev=0).zip
          asset_name: prowl-source-$(git describe --tags --abbrev=0).zip
          asset_content_type: application/zip