name: Release Build and Attach

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Attach Artifacts
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
  
      - name: Version
        run: go version
  
      - name: Build
        run: go build -v ./...
  
      - name: Test
        run: go test -v ./...

      - name: Pack the thing
        run: zip prowl-linux-x64.zip ./prowl
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: prowl-linux-x64.zip
            path: ./prowl-linux-x64.zip
    
      # Attach artifacts to the release
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./prowl-linux-x64.zip
          asset_name: prowl-linux-x64.zip
          asset_content_type: application/zip